# Generated by Django 3.2.9 on 2021-12-02 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('LIKE', 'like'), ('COMMENTAIRE', 'commentaire'), ('PARTAGE', 'partage')], max_length=100)),
                ('description', models.TextField()),
                ('date_de_creation', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('date_de_creation', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artiste',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_d_artiste', models.CharField(max_length=100)),
                ('biographie', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BadgeArtiste',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='BadgeFan',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='DevenirMembre',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_d_inscription', models.DateTimeField(auto_now=True)),
                ('remarque', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('biographie', models.TextField()),
                ('badges', models.ManyToManyField(to='api.BadgeFan')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('date_de_publication', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.CharField(max_length=100)),
                ('y', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TypeArtiste',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOuvrage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('pseudo', models.CharField(blank=True, max_length=100, null=True)),
                ('sexe', models.CharField(choices=[('HOMME', 'homme'), ('FEMME', 'femme')], default='FEMME', max_length=20)),
                ('mail', models.CharField(max_length=200)),
                ('tel', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=500)),
                ('date_de_naissance', models.DateField()),
                ('lieu_de_naissance', models.CharField(max_length=100)),
                ('photo_profil', models.CharField(blank=True, max_length=1000, null=True)),
                ('photo_couverture', models.CharField(blank=True, max_length=1000, null=True)),
                ('date_de_creation', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ValidationEmail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code_de_validation', models.CharField(max_length=1000)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_de_creation', models.DateTimeField(auto_now=True)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.artiste')),
                ('publications', models.ManyToManyField(to='api.Publication')),
            ],
        ),
        migrations.CreateModel(
            name='Ouvrage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.CharField(blank=True, max_length=1000, null=True)),
                ('url', models.CharField(blank=True, max_length=1000, null=True)),
                ('date_de_creation', models.DateTimeField(auto_now=True)),
                ('createurs', models.ManyToManyField(to='api.Artiste')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.typeouvrage')),
            ],
        ),
        migrations.CreateModel(
            name='FanClub',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_de_creation', models.DateTimeField(auto_now=True)),
                ('membres', models.ManyToManyField(through='api.DevenirMembre', to='api.Fan')),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.artiste')),
                ('publications', models.ManyToManyField(to='api.Publication')),
            ],
        ),
        migrations.AddField(
            model_name='fan',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.utilisateur'),
        ),
        migrations.AddField(
            model_name='devenirmembre',
            name='fan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fan'),
        ),
        migrations.AddField(
            model_name='devenirmembre',
            name='fanClub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fanclub'),
        ),
        migrations.CreateModel(
            name='Contenu',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('IMAGE', 'image'), ('VIDEO', 'video'), ('audio', 'audio')], max_length=100)),
                ('description', models.TextField()),
                ('source', models.CharField(max_length=500)),
                ('date_de_creation', models.DateTimeField(auto_now=True)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.publication')),
            ],
        ),
        migrations.AddField(
            model_name='artiste',
            name='badges',
            field=models.ManyToManyField(to='api.BadgeArtiste'),
        ),
        migrations.AddField(
            model_name='artiste',
            name='type_artiste',
            field=models.ManyToManyField(to='api.TypeArtiste'),
        ),
        migrations.AddField(
            model_name='artiste',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.utilisateur'),
        ),
    ]
