# Generated by Django 3.2.9 on 2021-12-10 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AAUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('firstName', models.CharField(max_length=100)),
                ('pseudo', models.CharField(blank=True, max_length=100, null=True)),
                ('sex', models.CharField(choices=[('HOMME', 'homme'), ('FEMME', 'femme')], default='FEMME', max_length=20)),
                ('biographie', models.TextField(blank=True, null=True)),
                ('email', models.CharField(max_length=200)),
                ('tel', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('dateOfBirth', models.DateField()),
                ('placeOfBirth', models.CharField(max_length=100)),
                ('profilePicture', models.CharField(blank=True, max_length=1000, null=True)),
                ('coverPicture', models.CharField(blank=True, max_length=1000, null=True)),
                ('creationDate', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('LIKE', 'like'), ('COMMENTAIRE', 'commentaire'), ('PARTAGE', 'partage')], max_length=100)),
                ('description', models.TextField()),
                ('creationDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('creationDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('stageName', models.CharField(blank=True, max_length=100, null=True)),
                ('aaUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.aauser')),
            ],
        ),
        migrations.CreateModel(
            name='ArtistBadge',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ArtistType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BecomeMember',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('inscriptionDate', models.DateTimeField(auto_now=True)),
                ('remark', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('aaUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.aauser')),
            ],
        ),
        migrations.CreateModel(
            name='FanBadge',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('publicationDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.CharField(max_length=100)),
                ('y', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.CharField(blank=True, max_length=1000, null=True)),
                ('url', models.CharField(blank=True, max_length=1000, null=True)),
                ('creationDate', models.DateTimeField(auto_now=True)),
                ('createurs', models.ManyToManyField(to='api.Artist')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.worktype')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('creationDate', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.artist')),
                ('publications', models.ManyToManyField(to='api.Publication')),
            ],
        ),
        migrations.CreateModel(
            name='FanClub',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('creationDate', models.DateTimeField(auto_now=True)),
                ('members', models.ManyToManyField(through='api.BecomeMember', to='api.Fan')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.artist')),
                ('publications', models.ManyToManyField(to='api.Publication')),
            ],
        ),
        migrations.AddField(
            model_name='fan',
            name='badges',
            field=models.ManyToManyField(blank=True, null=True, to='api.FanBadge'),
        ),
        migrations.CreateModel(
            name='EmailValidation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('validationCode', models.CharField(max_length=1000)),
                ('aaUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.aauser')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('IMAGE', 'image'), ('VIDEO', 'video'), ('audio', 'audio')], max_length=100)),
                ('description', models.TextField()),
                ('source', models.CharField(max_length=500)),
                ('creationDate', models.DateTimeField(auto_now=True)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.publication')),
            ],
        ),
        migrations.AddField(
            model_name='becomemember',
            name='fan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fan'),
        ),
        migrations.AddField(
            model_name='becomemember',
            name='fanClub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fanclub'),
        ),
        migrations.AddField(
            model_name='artist',
            name='badges',
            field=models.ManyToManyField(blank=True, null=True, to='api.ArtistBadge'),
        ),
        migrations.AddField(
            model_name='artist',
            name='type',
            field=models.ManyToManyField(blank=True, null=True, to='api.ArtistType'),
        ),
    ]
