# Generated by Django 3.2.9 on 2021-12-02 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
