# Generated by Django 3.2.9 on 2021-12-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_biographie_aauser_biography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aauser',
            name='profilePicture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
