# Generated by Django 3.2.9 on 2021-12-02 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_utilisateur_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='mail',
            new_name='email',
        ),
    ]
