# Generated by Django 3.2.9 on 2021-12-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_aauser_profilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aauser',
            name='coverPicture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
