# Generated by Django 3.2.9 on 2021-12-03 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_mail_utilisateur_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artiste',
            name='badges',
            field=models.ManyToManyField(blank=True, null=True, to='api.BadgeArtiste'),
        ),
        migrations.AlterField(
            model_name='artiste',
            name='biographie',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artiste',
            name='nom_d_artiste',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='artiste',
            name='type_artiste',
            field=models.ManyToManyField(blank=True, null=True, to='api.TypeArtiste'),
        ),
    ]
