# Generated by Django 3.2.9 on 2021-12-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_aauser_coverpicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aauser',
            name='profilePicture',
            field=models.ImageField(blank=True, null=True, upload_to='upload/'),
        ),
    ]
