# Generated by Django 3.2.9 on 2021-12-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211203_0035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artiste',
            name='biographie',
        ),
        migrations.RemoveField(
            model_name='fan',
            name='biographie',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='biographie',
            field=models.TextField(blank=True, null=True),
        ),
    ]
