# Generated by Django 3.2.9 on 2021-12-12 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_aauser_profilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aauser',
            name='coverPicture',
            field=models.ImageField(blank=True, null=True, upload_to='user_<django.db.models.fields.BigAutoField>/'),
        ),
        migrations.AlterField(
            model_name='aauser',
            name='profilePicture',
            field=models.ImageField(blank=True, null=True, upload_to='user_<django.db.models.fields.BigAutoField>/'),
        ),
    ]
