# Generated by Django 3.2.9 on 2021-12-12 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20211212_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aauser',
            name='coverPicture',
            field=models.ImageField(blank=True, null=True, upload_to='coverPicture/'),
        ),
        migrations.AlterField(
            model_name='aauser',
            name='profilePicture',
            field=models.ImageField(blank=True, null=True, upload_to='profilePicture/'),
        ),
    ]
