# Generated by Django 3.2.9 on 2021-12-20 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_content_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='source',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
