# Generated by Django 3.2.9 on 2021-12-21 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20211220_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='publication',
        ),
        migrations.AddField(
            model_name='publication',
            name='contents',
            field=models.ManyToManyField(blank=True, null=True, to='api.Content'),
        ),
    ]
