# Generated by Django 3.2.9 on 2021-12-21 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20211221_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='userPublisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.aauser'),
        ),
    ]
