# Generated by Django 3.2.9 on 2021-12-21 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_publication_userpublisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='userPublisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.aauser'),
        ),
    ]
